// ─── Platform config ──────────────────────────────────────────────────────────
const PLATFORMS = {
  instagram: {
    domains:    ['.instagram.com', 'instagram.com'],
    authCookie: 'sessionid',
    label:      'Instagram',
  },
  facebook: {
    domains:    ['.facebook.com', 'facebook.com'],
    authCookie: 'c_user',
    label:      'Facebook',
  },
  tiktok: {
    domains:    ['.tiktok.com', 'tiktok.com'],
    authCookie: 'sessionid',
    label:      'TikTok',
  },
  youtube: {
    domains:    ['.youtube.com', 'youtube.com'],
    authCookie: 'LOGIN_INFO',
    label:      'YouTube',
  },
};

// ─── DOM refs ─────────────────────────────────────────────────────────────────
const syncBtn        = document.getElementById('sync-btn');
const toast          = document.getElementById('toast');
const lastSyncLabel  = document.getElementById('last-sync-label');
const autoToggle     = document.getElementById('auto-sync-toggle');
const mainPanel      = document.getElementById('main-panel');
const settingsPanel  = document.getElementById('settings-panel');
const openSettings   = document.getElementById('open-settings');
const backBtn        = document.getElementById('back-btn');
const serverUrlInput = document.getElementById('server-url');
const apiKeyInput    = document.getElementById('api-key');
const saveSettings   = document.getElementById('save-settings');
const toastSettings  = document.getElementById('toast-settings');

// ─── Init ─────────────────────────────────────────────────────────────────────
async function init() {
  const stored = await chrome.storage.local.get(['serverUrl', 'apiKey', 'autoSync', 'lastSync']);
  if (stored.serverUrl) serverUrlInput.value = stored.serverUrl;
  if (stored.apiKey)    apiKeyInput.value    = stored.apiKey;
  autoToggle.checked = stored.autoSync ?? true;
  if (stored.lastSync) lastSyncLabel.textContent = 'Última sincronización: ' + new Date(stored.lastSync).toLocaleString('es');

  await checkAllPlatforms();
}

// ─── Check login status for each platform ─────────────────────────────────────
async function checkAllPlatforms() {
  for (const [id, cfg] of Object.entries(PLATFORMS)) {
    const dot  = document.getElementById(`status-dot-${id}`);
    const text = document.getElementById(`status-text-${id}`);
    dot.className  = 'status-dot idle';
    text.textContent = 'Verificando...';

    try {
      const cookies = await getAllCookiesForPlatform(id);
      const authCk  = cookies.find(c => c.name === cfg.authCookie);

      if (authCk) {
        dot.className    = 'status-dot ok';
        text.textContent = 'Sesión activa ✓';
      } else {
        dot.className    = 'status-dot err';
        text.textContent = 'No has iniciado sesión';
      }
    } catch {
      dot.className    = 'status-dot warn';
      text.textContent = 'Error al verificar';
    }
  }
}

// ─── Get all cookies for a platform ──────────────────────────────────────────
async function getAllCookiesForPlatform(platformId) {
  const cfg = PLATFORMS[platformId];
  let all = [];
  for (const domain of cfg.domains) {
    const ck = await chrome.cookies.getAll({ domain });
    all = all.concat(ck);
  }
  // Deduplicate by name
  const seen = new Set();
  return all.filter(c => {
    if (seen.has(c.name)) return false;
    seen.add(c.name);
    return true;
  });
}

// ─── Convert chrome.cookies to Netscape format ────────────────────────────────
function toNetscapeFormat(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by WSSD Cookie Sync Extension', ''];
  for (const c of cookies) {
    const domain     = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
    const includeSD  = 'TRUE';
    const path       = c.path || '/';
    const secure     = c.secure ? 'TRUE' : 'FALSE';
    const expiry     = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    const name       = c.name;
    const value      = c.value;
    lines.push(`${domain}\t${includeSD}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`);
  }
  return lines.join('\n');
}

// ─── Sync to server ───────────────────────────────────────────────────────────
async function syncToServer() {
  const { serverUrl, apiKey } = await chrome.storage.local.get(['serverUrl', 'apiKey']);
  if (!serverUrl || !apiKey) {
    showToast(toast, '⚠️ Configura el servidor y la API key primero', 'err');
    return;
  }

  syncBtn.disabled = true;
  syncBtn.classList.add('syncing');
  syncBtn.querySelector('span') && (syncBtn.querySelector('span').textContent = 'Sincronizando...');
  // Update button text
  const btnText = syncBtn.childNodes[syncBtn.childNodes.length - 1];
  const originalText = btnText.textContent;
  btnText.textContent = ' Sincronizando...';

  try {
    // Gather all cookies for all platforms
    const allCookies = [];
    const results = {};

    for (const [id, cfg] of Object.entries(PLATFORMS)) {
      const cookies = await getAllCookiesForPlatform(id);
      const authCk  = cookies.find(c => c.name === cfg.authCookie);
      results[id]   = !!authCk;
      allCookies.push(...cookies);
    }

    // Deduplicate all cookies by domain+name
    const seen = new Set();
    const unique = allCookies.filter(c => {
      const key = `${c.domain}|${c.name}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });

    const payload = {
      cookies: unique.map(c => ({
        domain:   c.domain.startsWith('.') ? c.domain : '.' + c.domain,
        name:     c.name,
        value:    c.value,
        path:     c.path || '/',
        secure:   c.secure,
        expiry:   c.expirationDate ? Math.floor(c.expirationDate) : 0,
      })),
      platforms: results,
    };

    const url = serverUrl.replace(/\/$/, '') + '/sync-cookies';
    const res = await fetch(url, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'X-API-Key': apiKey },
      body:    JSON.stringify(payload),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Error ${res.status}: ${err}`);
    }

    // Update last sync time
    const now = Date.now();
    await chrome.storage.local.set({ lastSync: now });
    lastSyncLabel.textContent = 'Última sincronización: ' + new Date(now).toLocaleString('es');

    // Count synced platforms
    const synced = Object.values(results).filter(Boolean).length;
    showToast(toast, `✅ ${synced} plataforma${synced !== 1 ? 's' : ''} sincronizada${synced !== 1 ? 's' : ''}`, 'ok');

    await checkAllPlatforms();

  } catch (e) {
    showToast(toast, '❌ ' + e.message, 'err');
  } finally {
    syncBtn.disabled = false;
    syncBtn.classList.remove('syncing');
    btnText.textContent = originalText;
  }
}

// ─── Toast helper ─────────────────────────────────────────────────────────────
function showToast(el, msg, type) {
  el.textContent  = msg;
  el.className    = `toast ${type}`;
  el.style.display = 'block';
  setTimeout(() => { el.style.display = 'none'; }, 4000);
}

// ─── Events ───────────────────────────────────────────────────────────────────
syncBtn.addEventListener('click', syncToServer);

autoToggle.addEventListener('change', async () => {
  await chrome.storage.local.set({ autoSync: autoToggle.checked });
  // Notify background worker
  chrome.runtime.sendMessage({ type: 'AUTO_SYNC_CHANGED', value: autoToggle.checked });
});

openSettings.addEventListener('click', () => {
  mainPanel.style.display = 'none';
  settingsPanel.style.display = 'block';
});

backBtn.addEventListener('click', () => {
  mainPanel.style.display = 'block';
  settingsPanel.style.display = 'none';
});

saveSettings.addEventListener('click', async () => {
  const url = serverUrlInput.value.trim();
  const key = apiKeyInput.value.trim();
  if (!url || !key) {
    showToast(toastSettings, '⚠️ Completa todos los campos', 'err');
    return;
  }
  await chrome.storage.local.set({ serverUrl: url, apiKey: key });
  showToast(toastSettings, '✅ Configuración guardada', 'ok');
});

// ─── Start ────────────────────────────────────────────────────────────────────
init();
