"""
WSSD Cookie Refresher
=====================
Mantiene cookies/cookies.txt actualizado para que el extractor pueda
descargar desde Instagram, TikTok y Facebook sin depender de ningún browser.

Variables de entorno necesarias:
  IG_EMAIL      — email de cuenta de servicio en Instagram
  IG_PASSWORD   — contraseña de esa cuenta
  TT_SESSIONID  — sessionid de TikTok (dura ~30-60 días, obtenerlo desde DevTools)
  FB_COOKIES    — "xs=valor;c_user=valor" (opcional, para Facebook privado)
  REFRESH_INTERVAL_H — horas entre refresco (default: 12)

En producción: estos valores van como secrets/env vars en el hosting (Railway,
Fly.io, DigitalOcean App Platform, etc.). Nunca se hardcodean en el código.
"""

import os
import sys
import time
import logging
import http.cookiejar
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [cookie-refresher] %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)

COOKIES_FILE      = Path("/cookies/cookies.txt")
REFRESH_INTERVAL  = int(os.environ.get("REFRESH_INTERVAL_H", "12")) * 3600


# ─────────────────────────────────────────────────────────────
# Netscape cookies.txt writer
# ─────────────────────────────────────────────────────────────
def _cookie_line(domain, path, secure, expires, name, value) -> str:
    flag    = "TRUE" if domain.startswith(".") else "FALSE"
    secure  = "TRUE" if secure else "FALSE"
    expires = str(int(expires)) if expires else str(int(time.time()) + 86400 * 60)
    return "\t".join([domain, flag, path, secure, expires, name, value])


def _write_netscape(cookies: list[dict], mode: str = "w") -> None:
    COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
    with COOKIES_FILE.open(mode) as f:
        if mode == "w":
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by WSSD Cookie Refresher — DO NOT EDIT MANUALLY\n\n")
        for c in cookies:
            f.write(_cookie_line(
                c.get("domain", ""),
                c.get("path", "/"),
                c.get("secure", False),
                c.get("expires", 0),
                c["name"],
                c["value"],
            ) + "\n")


# ─────────────────────────────────────────────────────────────
# Instagram via instaloader (no browser required)
# ─────────────────────────────────────────────────────────────
def refresh_instagram() -> bool:
    email    = os.environ.get("IG_EMAIL", "").strip()
    password = os.environ.get("IG_PASSWORD", "").strip()
    if not (email and password):
        log.info("IG_EMAIL / IG_PASSWORD no configurados — omitiendo Instagram")
        return False

    try:
        import instaloader
        log.info("Iniciando sesión en Instagram como %s …", email)
        L = instaloader.Instaloader()
        L.login(email, password)

        raw = L.context._session.cookies
        cookies = []
        for c in raw:
            if "instagram" not in (c.domain or ""):
                continue
            domain = c.domain if c.domain.startswith(".") else f".{c.domain}"
            cookies.append({
                "domain":  domain,
                "path":    c.path or "/",
                "secure":  c.secure,
                "expires": c.expires or 0,
                "name":    c.name,
                "value":   c.value,
            })

        if not cookies:
            log.warning("Login OK pero no se obtuvieron cookies de Instagram")
            return False

        _write_netscape(cookies, mode="w")
        log.info("✅ Instagram: %d cookies escritas en %s", len(cookies), COOKIES_FILE)
        return True

    except Exception as e:
        log.error("❌ Error al refrescar cookies de Instagram: %s", e)
        return False


# ─────────────────────────────────────────────────────────────
# TikTok via sessionid env var
# ─────────────────────────────────────────────────────────────
def refresh_tiktok() -> bool:
    sessionid = os.environ.get("TT_SESSIONID", "").strip()
    if not sessionid:
        log.info("TT_SESSIONID no configurado — omitiendo TikTok")
        return False

    # Check if we already have a fresh TikTok sessionid in the file
    try:
        existing = COOKIES_FILE.read_text() if COOKIES_FILE.exists() else ""
        if sessionid in existing:
            log.info("TikTok sessionid ya está en cookies.txt")
            return True
    except Exception:
        pass

    mode = "a" if COOKIES_FILE.exists() else "w"
    expires = int(time.time()) + 86400 * 60  # 60 días

    cookies = [
        {"domain": ".tiktok.com", "path": "/", "secure": True,
         "expires": expires, "name": "sessionid", "value": sessionid},
        {"domain": ".tiktok.com", "path": "/", "secure": True,
         "expires": expires, "name": "sessionid_ss", "value": sessionid},
    ]

    if mode == "w":
        _write_netscape(cookies, mode="w")
    else:
        COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
        with COOKIES_FILE.open("a") as f:
            for c in cookies:
                f.write(_cookie_line(
                    c["domain"], c["path"], c["secure"],
                    c["expires"], c["name"], c["value"]
                ) + "\n")

    log.info("✅ TikTok: sessionid escrito en %s", COOKIES_FILE)
    return True


# ─────────────────────────────────────────────────────────────
# Facebook via raw cookie string env var
# ─────────────────────────────────────────────────────────────
def refresh_facebook() -> bool:
    raw = os.environ.get("FB_COOKIES", "").strip()
    if not raw:
        log.info("FB_COOKIES no configurado — omitiendo Facebook")
        return False

    # Format: "xs=abc123;c_user=456789;..."
    try:
        pairs = [p.strip() for p in raw.split(";") if "=" in p]
        expires = int(time.time()) + 86400 * 30
        cookies = [
            {"domain": ".facebook.com", "path": "/", "secure": True,
             "expires": expires, "name": k, "value": v}
            for p in pairs
            for k, v in [p.split("=", 1)]
        ]
        mode = "a" if COOKIES_FILE.exists() else "w"
        if mode == "w":
            _write_netscape(cookies, mode="w")
        else:
            COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
            with COOKIES_FILE.open("a") as f:
                for c in cookies:
                    f.write(_cookie_line(
                        c["domain"], c["path"], c["secure"],
                        c["expires"], c["name"], c["value"]
                    ) + "\n")
        log.info("✅ Facebook: %d cookies escritas", len(cookies))
        return True
    except Exception as e:
        log.error("❌ Error al escribir cookies de Facebook: %s", e)
        return False


# ─────────────────────────────────────────────────────────────
# Main loop
# ─────────────────────────────────────────────────────────────
def run_once() -> None:
    log.info("── Iniciando ciclo de refresco de cookies ──")
    ig_ok = refresh_instagram()
    tt_ok = refresh_tiktok()
    fb_ok = refresh_facebook()

    if not (ig_ok or tt_ok or fb_ok):
        log.warning(
            "No hay credenciales configuradas. "
            "Define IG_EMAIL+IG_PASSWORD, TT_SESSIONID o FB_COOKIES en el .env"
        )
    else:
        log.info("── Ciclo completado. Próximo refresco en %dh ──", REFRESH_INTERVAL // 3600)


if __name__ == "__main__":
    run_once()
    while True:
        time.sleep(REFRESH_INTERVAL)
        run_once()
